version: '3.1'

services:

  db:
    image: 'mysql:5.6'
    restart: always
    volumes: 
      - './data:/var/lib/mysql:rw'
      - './config-felix-orduz.cnf:/etc/mysql/conf.d/config-felix-orduz.cnf'
    ports: 
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'change-me'
    networks:
      - mysql5.6-test
networks:
  mysql5.6-test: